# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

graph_coloring_dsatur <- function(adj_list) {
    .Call(`_GCMER_graph_coloring_dsatur`, adj_list)
}

graph_coloring_msc <- function(adj_list) {
    .Call(`_GCMER_graph_coloring_msc`, adj_list)
}

graph_coloring_lmxrlf <- function(adj_list) {
    .Call(`_GCMER_graph_coloring_lmxrlf`, adj_list)
}

graph_coloring_hybrid_dsatur_tabucol <- function(adj_list) {
    .Call(`_GCMER_graph_coloring_hybrid_dsatur_tabucol`, adj_list)
}

graph_coloring_hybrid_lmxrlf_tabucol <- function(adj_list) {
    .Call(`_GCMER_graph_coloring_hybrid_lmxrlf_tabucol`, adj_list)
}

graph_coloring_tabucol <- function(adj_list, k, tabu_size = 25L, rep = 100L, nbmax = 1000L) {
    .Call(`_GCMER_graph_coloring_tabucol`, adj_list, k, tabu_size, rep, nbmax)
}

